package laundry;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author damhiesax
 */
public class BankDetails extends javax.swing.JFrame {
 DbConnect dbcon = new DbConnect();
    DefaultComboBoxModel combo,combo2,combo3;
      DefaultTableModel dataSet;
      String  pro=""; 
      int j=0;
      double bal;
      Vector<Integer> id;
       FormatDate fDate = new FormatDate();
       Date d;
       double pay=0.0,rev=0.0;
    /**
     * Creates new form BankDetails
     */
    public BankDetails() {
        initComponents();
          jRadioButton1.setSelected(true);
        jRadioButton1ActionPerformed(null);
        getDetails();
         getTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        dateChooserCombo3 = new datechooser.beans.DateChooserCombo();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Date");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 30, 40, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Bank Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 60, 80, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Branch Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 90, 100, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Account No");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 120, 90, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Process");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 150, 60, 15);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setText("Deposit");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(130, 150, 90, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setText("Withdraw");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(220, 150, 110, 23);

        dateChooserCombo1.setFormat(2);
        dateChooserCombo1.addCommitListener(new datechooser.events.CommitListener() {
            public void onCommit(datechooser.events.CommitEvent evt) {
                dateChooserCombo1OnCommit(evt);
            }
        });
        jPanel1.add(dateChooserCombo1);
        dateChooserCombo1.setBounds(140, 30, 190, 20);

        dateChooserCombo2.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserCombo2.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            dateChooserCombo2OnCommit(evt);
        }
    });
    jPanel1.add(dateChooserCombo2);
    dateChooserCombo2.setBounds(210, 300, 110, 20);

    dateChooserCombo3.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
dateChooserCombo3.addCommitListener(new datechooser.events.CommitListener() {
    public void onCommit(datechooser.events.CommitEvent evt) {
        dateChooserCombo3OnCommit(evt);
    }
    });
    jPanel1.add(dateChooserCombo3);
    dateChooserCombo3.setBounds(350, 300, 110, 20);

    jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel6.setText("Amount");
    jPanel1.add(jLabel6);
    jLabel6.setBounds(60, 180, 60, 15);

    jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            jTextField4KeyReleased(evt);
        }
    });
    jPanel1.add(jTextField4);
    jTextField4.setBounds(150, 180, 180, 20);

    jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
    jButton1.setText("Save");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton1);
    jButton1.setBounds(210, 210, 80, 27);

    jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel8.setText("Bank Name");
    jPanel1.add(jLabel8);
    jLabel8.setBounds(380, 30, 90, 10);

    jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel9.setText("Branch Name");
    jPanel1.add(jLabel9);
    jLabel9.setBounds(370, 60, 100, 10);

    jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel10.setText("Account No");
    jPanel1.add(jLabel10);
    jLabel10.setBounds(380, 90, 71, 10);
    jPanel1.add(jTextField5);
    jTextField5.setBounds(490, 30, 160, 20);
    jPanel1.add(jTextField6);
    jTextField6.setBounds(490, 60, 160, 20);
    jPanel1.add(jTextField7);
    jTextField7.setBounds(490, 90, 160, 20);

    jButton2.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
    jButton2.setText("ADD");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton2);
    jButton2.setBounds(580, 150, 80, 27);

    jTextField8.setText("0");
    jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            jTextField8KeyTyped(evt);
        }
        public void keyReleased(java.awt.event.KeyEvent evt) {
            jTextField8KeyReleased(evt);
        }
    });
    jPanel1.add(jTextField8);
    jTextField8.setBounds(490, 120, 160, 20);

    jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jPanel1.add(jLabel11);
    jLabel11.setBounds(350, 10, 350, 180);

    jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jPanel1.add(jComboBox1);
    jComboBox1.setBounds(140, 60, 190, 21);

    jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jPanel1.add(jComboBox2);
    jComboBox2.setBounds(140, 90, 190, 21);

    jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jPanel1.add(jComboBox3);
    jComboBox3.setBounds(140, 120, 190, 21);

    jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jPanel1.add(jLabel7);
    jLabel7.setBounds(20, 10, 320, 250);

    jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel12.setText("Opening Balance");
    jPanel1.add(jLabel12);
    jLabel12.setBounds(370, 120, 110, 15);

    jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jButton4.setText("Export To Excel");
    jPanel1.add(jButton4);
    jButton4.setBounds(40, 300, 160, 23);

    jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jButton5.setText("Load Report");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton5);
    jButton5.setBounds(580, 300, 120, 23);

    jLabel13.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
    jLabel13.setText("Date Between");
    jPanel1.add(jLabel13);
    jLabel13.setBounds(250, 270, 120, 20);

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    ));
    jTable1.setColumnSelectionAllowed(true);
    jScrollPane1.setViewportView(jTable1);
    jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

    jPanel1.add(jScrollPane1);
    jScrollPane1.setBounds(40, 330, 660, 90);

    jButton6.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
    jButton6.setText("Remove");
    jButton6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton6ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton6);
    jButton6.setBounds(40, 430, 100, 27);

    jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel14.setText("Opening Balance");
    jPanel1.add(jLabel14);
    jLabel14.setBounds(130, 460, 120, 15);

    jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel15.setText("Total Receipt");
    jPanel1.add(jLabel15);
    jLabel15.setBounds(130, 490, 100, 15);

    jTextField1.setEditable(false);
    jTextField1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.add(jTextField1);
    jTextField1.setBounds(250, 460, 160, 20);

    jTextField2.setEditable(false);
    jTextField2.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.add(jTextField2);
    jTextField2.setBounds(250, 490, 160, 20);

    jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel16.setText("Total payments");
    jPanel1.add(jLabel16);
    jLabel16.setBounds(450, 460, 110, 15);

    jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel17.setText("Closing Balance");
    jPanel1.add(jLabel17);
    jLabel17.setBounds(450, 490, 110, 15);

    jTextField3.setEditable(false);
    jTextField3.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.add(jTextField3);
    jTextField3.setBounds(560, 460, 140, 20);

    jTextField9.setEditable(false);
    jTextField9.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.add(jTextField9);
    jTextField9.setBounds(560, 490, 140, 20);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if(jTextField5.getText().isEmpty()||jTextField6.getText().isEmpty()||jTextField7.getText().isEmpty()||jTextField8.getText().isEmpty()){
      JOptionPane.showMessageDialog(rootPane, "Make You Supply All Neccessary Info");
          return;
      }
       insert(); 
       getDetails();
       getTable();
       jTextField5.setText("");
       jTextField6.setText("");
       jTextField7.setText("");
       jTextField7.setText("0");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
            Object ch = evt.getKeyChar();
            String cha = ch.toString();
             if (!"1234567890\b\n".contains(cha)) {
                jTextField4.setText(jTextField4.getText().substring(0, (jTextField4.getText().length() - 1)));
                return;
            }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8KeyTyped

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
            Object ch = evt.getKeyChar();
            String cha = ch.toString();
             if (!"1234567890\b\n".contains(cha)) {
                jTextField8.setText(jTextField8.getText().substring(0, (jTextField8.getText().length() - 1)));
                return;
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8KeyReleased

    private void dateChooserCombo1OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserCombo1OnCommit

    }//GEN-LAST:event_dateChooserCombo1OnCommit

    private void dateChooserCombo2OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserCombo2OnCommit

        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserCombo2OnCommit

    private void dateChooserCombo3OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserCombo3OnCommit
        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserCombo3OnCommit

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if(jRadioButton1.isSelected())
       pro="deposit"; 
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        if(jRadioButton2.isSelected())
       pro="withdraw"; 
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      insert2();
      getTable();
      getDetails();
      jTextField4.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      remove();
      getDetails();
      getTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
   j=0;
        dataSet = new DefaultTableModel();
        dataSet.addColumn("S/N");
        dataSet.addColumn("Name");
        dataSet.addColumn("Branch");
       dataSet.addColumn("AccNO");
       dataSet.addColumn("Opening Bal");
        dataSet.addColumn("Deposit");
        dataSet.addColumn("Withdraw");
         dataSet.addColumn("Closing Bal");
          dataSet.addColumn("Date");
          
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
       SimpleDateFormat dateFormat2 = new SimpleDateFormat("dd-MM-yy");
        
       String startDate=dateChooserCombo2.getText() ;
        d = new Date(startDate);
        startDate=dateFormat2.format(d);
              startDate = fDate.getDateFormat(startDate);
          String  stopDate=dateChooserCombo3.getText();
           d = new Date(stopDate);
            stopDate=dateFormat2.format(d);
             stopDate = fDate.getDateFormat(stopDate);
          
         
           
            boolean chkIt = fDate.checkDate(startDate, stopDate);
            if (!chkIt) {
                JOptionPane.showMessageDialog(rootPane, "Date not properly selected\nMake sure you selected a valid date");
                return;
            }
            do {
                if (stopDate.equalsIgnoreCase(startDate)) {
                break;
                }
                d = new Date(startDate);
                gatData(dateFormat.format(d));
                 startDate = fDate.getDate(startDate);
            } while ((!stopDate.equalsIgnoreCase(startDate)));
            d = new Date(startDate);
            gatData(dateFormat.format(d));
                JOptionPane.showMessageDialog(rootPane, "<html>Data Cleared <i>From</i> <b>"+dateChooserCombo2.getText()+"</b> <i>To</i> <b>"+dateChooserCombo3.getText()+"</b>");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private datechooser.beans.DateChooserCombo dateChooserCombo3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
void insert(){
 try {
       dbcon.rs = dbcon.st.executeQuery("select * from bank where bank_name='"+jTextField5.getText()+"' and branch_name='"+jTextField6.getText()+"' and acc_no='"+jTextField7.getText()+"'");
            if(dbcon.rs.next()){
           JOptionPane.showMessageDialog(rootPane, "Account Exist");
           return;
            }
     
                dbcon.ps = dbcon.con.prepareStatement("Insert into bank (bank_name,branch_name,acc_no,open_bal,process,amt,closing_bal,date) VALUES(?,?,?,?,?,?,?,?)");
                dbcon.ps.setString(1, jTextField5.getText());
                dbcon.ps.setString(2, jTextField6.getText());
                dbcon.ps.setString(3, jTextField7.getText());
                dbcon.ps.setString(4, "0");
                  dbcon.ps.setString(5, "deposit");
                dbcon.ps.setString(6, jTextField8.getText());
                dbcon.ps.setString(7, jTextField8.getText());
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
                 Date d=new Date();
                 d=new Date(d.getTime());
                dbcon.ps.setString(8, dateFormat.format(d));
                dbcon.ps.execute();
                  JOptionPane.showMessageDialog(rootPane, "Bank Info Saved");
            } catch (Exception ex) {
                ex.printStackTrace();
            }
 
}
void insert2(){
 double bal=0.0;
 double amt=0.0;
 double amt2=0.0;
    try {
       dbcon.rs = dbcon.st.executeQuery("select * from bank where bank_name='"+jComboBox1.getSelectedItem().toString()+"' and branch_name='"+jComboBox2.getSelectedItem()+"' and acc_no='"+jComboBox3.getSelectedItem().toString()+"'");
            if(dbcon.rs.next()){
             bal=dbcon.rs.getDouble("closing_bal");
            }else{
            JOptionPane.showMessageDialog(rootPane, "Invalid Acc Selection");
            }
              if(pro.equalsIgnoreCase("deposit")){
             amt=Double.parseDouble(jTextField4.getText());
             amt2=0;
             }else{
             amt2=Double.parseDouble(jTextField4.getText());
             amt=0;
             }
                dbcon.ps = dbcon.con.prepareStatement("Insert into bank (bank_name,branch_name,acc_no,open_bal,process,amt,closing_bal,date) VALUES(?,?,?,?,?,?,?,?)");
                dbcon.ps.setString(1, jComboBox1.getSelectedItem().toString());
                dbcon.ps.setString(2, jComboBox2.getSelectedItem().toString());
                dbcon.ps.setString(3, jComboBox3.getSelectedItem().toString());
                dbcon.ps.setDouble(4, bal);
                  dbcon.ps.setString(5, pro );
                dbcon.ps.setString(6, jTextField4.getText());
                dbcon.ps.setDouble(7, bal+=(amt-amt2));
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
                 Date d=new Date();
                 d=new Date(d.getTime());
                dbcon.ps.setString(8, dateFormat.format(d));
                dbcon.ps.execute();
                JOptionPane.showMessageDialog(rootPane, "Bank Info Saved");
            } catch (Exception ex) {
                ex.printStackTrace();
            }
    jRadioButton1.setSelected(true);
        jRadioButton1ActionPerformed(null);
}

void getDetails(){
   combo=new DefaultComboBoxModel();
   combo2=new DefaultComboBoxModel();
           combo3=new DefaultComboBoxModel();
    try {
     dbcon.rs = dbcon.st.executeQuery("select * from bank");
            while(dbcon.rs.next()){
                if(combo.getIndexOf(dbcon.rs.getString("bank_name"))==-1)
                combo.addElement(dbcon.rs.getString("bank_name"));
                if(combo2.getIndexOf(dbcon.rs.getString("branch_name"))==-1)
                combo2.addElement(dbcon.rs.getString("branch_name"));
                if(combo3.getIndexOf(dbcon.rs.getString("acc_no"))==-1)
                combo3.addElement(dbcon.rs.getString("acc_no"));
            }  
            jComboBox1.setModel(combo);
            jComboBox2.setModel(combo2);
            jComboBox3.setModel(combo3);
    } catch (Exception e) {
    }
    
}
 void getTable(){
   j=0;
        dataSet = new DefaultTableModel();
        dataSet.addColumn("S/N");
        dataSet.addColumn("Name");
        dataSet.addColumn("Branch");
       dataSet.addColumn("AccNO");
       dataSet.addColumn("Opening Bal");
        dataSet.addColumn("Deposit");
        dataSet.addColumn("Withdraw");
         dataSet.addColumn("Closing Bal");
          dataSet.addColumn("Date");
          
        gatData("");
 }
 void gatData(String date){
     id= new Vector<>();
     pay=0.0;
     rev=0.0;
      bal=0.0;
     String process="";
     double amt=0,amt2=0;
   try {
       if(date.isEmpty()){
        dbcon.rs = dbcon.st.executeQuery("select * from bank");
        }else{
        dbcon.rs = dbcon.st.executeQuery("select * from bank where date='"+date+"'");
        }
           while (dbcon.rs.next()) { 
             process=dbcon.rs.getString("process");
             if(process.equalsIgnoreCase("deposit")){
             amt=dbcon.rs.getDouble("amt");
             pay+=amt;
             amt2=0;
             }else{
             amt2=dbcon.rs.getDouble("amt");
             rev+=amt2;
             amt=0;
             }
             id.addElement(dbcon.rs.getInt("id"));
            bal+=(amt-amt2);
                Object[] data = new Object[]{++j,dbcon.rs.getString("bank_name"),dbcon.rs.getString("branch_name"),dbcon.rs.getString("acc_no"),dbcon.rs.getString("open_bal"),amt,amt2,dbcon.rs.getString("closing_bal"),dbcon.rs.getString("date")};
               
                dataSet.addRow(data);
            }
                jTable1.setModel(dataSet);
                 jTextField1.setText("#"+jTable1.getValueAt(0, 4));
                jTextField9.setText("#"+bal);
                jTextField2.setText("#"+pay); 
                jTextField3.setText("#"+rev); 
   } catch (Exception e) {
        e.printStackTrace();
    }
 }
void remove(){
   try{
            dbcon.ps = dbcon.con.prepareStatement("DELETE FROM bank where id='" + id.elementAt(jTable1.getSelectedRow()) + "'");
            dbcon.ps.execute();
        } catch (Exception e) {
            System.out.println("red " + e.getMessage());
        }
}
}
