package laundry;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author damhiesax
 */
public class BillingCollection extends javax.swing.JFrame {
 DbConnect dbcon = new DbConnect();
Vector<String> data = new Vector<String>();
    String id;
    DefaultTableModel dataSet;
    int j;
    double advance;
    Date d;
    /**
     * Creates new form BillingCollection
     */
    public BillingCollection() {
        initComponents();
           SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
        d=new Date();
        d=new Date(d.getTime());
       jLabel14.setText(dateFormat.format(d));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField13 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Bill No");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 60, 60, 15);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 255, 204));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(80, 60, 77, 20);

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 60, 80, 27);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(40, 100, 150, 20);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(200, 100, 160, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Bill Amount");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 150, 80, 15);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.add(jTextField4);
        jTextField4.setBounds(200, 150, 160, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Advance");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 180, 70, 15);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(0, 204, 204));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(200, 180, 160, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Bill Balance");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 210, 90, 15);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.add(jTextField6);
        jTextField6.setBounds(200, 210, 160, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Tendered Amount");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 240, 120, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Tender Balance");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(100, 270, 115, 15);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(200, 240, 160, 20);

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.add(jTextField8);
        jTextField8.setBounds(200, 270, 160, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Bill Due Balance");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 300, 120, 15);

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.add(jTextField9);
        jTextField9.setBounds(200, 300, 160, 20);

        jButton2.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton2.setText("Print");
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 440, 80, 27);

        jButton3.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(180, 440, 66, 27);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Order Date");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(110, 340, 90, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Due Date");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(120, 360, 70, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Date Delivered");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(80, 380, 100, 15);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("ORDER DATE");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(210, 340, 150, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("DUE DATE");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(210, 360, 150, 14);

        jLabel14.setBackground(new java.awt.Color(204, 255, 204));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("DATE DELIVERED");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(210, 380, 160, 14);

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 50, 370, 460);

        jLabel15.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel15.setText("Billing Collection");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(350, 10, 240, 30);

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(410, 60, 510, 200);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Sub Total");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(670, 280, 90, 15);

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jTextField10);
        jTextField10.setBounds(850, 280, 60, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Discount");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(670, 320, 100, 15);

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jTextField11);
        jTextField11.setBounds(850, 310, 60, 20);

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jTextField12);
        jTextField12.setBounds(790, 310, 50, 20);

        jCheckBox1.setBackground(new java.awt.Color(204, 204, 255));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setText("URGENT");
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(750, 340, 80, 23);

        jTextField13.setEditable(false);
        jTextField13.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jTextField13);
        jTextField13.setBounds(840, 340, 70, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Total");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(670, 370, 50, 15);

        jTextField14.setEditable(false);
        jTextField14.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jTextField14);
        jTextField14.setBounds(840, 370, 70, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Net Total");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(670, 410, 90, 15);

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jTextField15);
        jTextField15.setBounds(840, 400, 70, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Advance");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(760, 440, 90, 15);

        jTextField16.setEditable(false);
        jTextField16.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jTextField16);
        jTextField16.setBounds(770, 400, 70, 20);

        jTextField17.setEditable(false);
        jTextField17.setBackground(new java.awt.Color(204, 204, 255));
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField17);
        jTextField17.setBounds(840, 430, 70, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Balance");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(760, 460, 60, 15);

        jTextField18.setEditable(false);
        jTextField18.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jTextField18);
        jTextField18.setBounds(840, 460, 70, 20);

        jLabel23.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel23.setText("Status -");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(420, 340, 70, 18);

        jButton4.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(440, 470, 70, 27);

        jLabel25.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel25.setText("status");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(480, 340, 180, 14);

        jLabel24.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));
        jPanel1.add(jLabel24);
        jLabel24.setBounds(410, 270, 510, 240);

        jLabel16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(400, 50, 530, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      j=0;
        dataSet = new DefaultTableModel();
        dataSet.addColumn("S/N");
        dataSet.addColumn("CATEGORY");
        dataSet.addColumn("ITEM");
        dataSet.addColumn("LEVEL");
        dataSet.addColumn("RATE");
         dataSet.addColumn("QTY");
          dataSet.addColumn("TOTAL");
        getBill();
        jTextField7.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
        if(jTextField7.getText().isEmpty()){
          jTextField5.setText(""+advance); 
          jTextField17.setText(""+advance);
           jTextField9.setText(""+jTextField6.getText()); 
          jTextField18.setText(""+jTextField6.getText());
        return;
        } 
        Object ch = evt.getKeyChar();
            String cha = ch.toString();
             if (!"1234567890\b\n".contains(cha)) {
                jTextField7.setText(jTextField7.getText().substring(0, (jTextField7.getText().length() - 1)));
                return;
            }
            jTextField5.setText(""+(advance+Double.parseDouble(jTextField7.getText()))); 
            jTextField17.setText(jTextField5.getText());
         jTextField9.setText(String.format("%.02f", Double.parseDouble(jTextField6.getText())-Double.parseDouble(jTextField7.getText())));
         if(Double.parseDouble(jTextField9.getText())<0.0){
             jTextField9.setText(""+0.0);
         }
           jTextField18.setText(jTextField9.getText()); 
         jTextField8.setText(String.format("%.02f", Double.parseDouble(jTextField7.getText())-Double.parseDouble(jTextField6.getText())));
          if(Double.parseDouble(jTextField8.getText())<0.0){
             jTextField8.setText(""+0.0);
         } 
           
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7KeyReleased

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          try {
                dbcon.ps = dbcon.con.prepareStatement("Insert into update_payment (bill_no,amt,balance,date) VALUES(?,?,?,?)");
                dbcon.ps.setString(1, jTextField1.getText());
                dbcon.ps.setString(2, jTextField7.getText());
                dbcon.ps.setString(3, jTextField9.getText());
                dbcon.ps.setString(4, jLabel14.getText());
                dbcon.ps.execute();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        jTextField7.setText("");
        JOptionPane.showMessageDialog(rootPane, "Update Successful");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     int a = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to close app");
        if (a == JOptionPane.YES_OPTION) {
           this.setVisible(false);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
       if(evt.getKeyChar()=='\n')
           jButton1ActionPerformed(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingCollection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingCollection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

void getBill(){
    advance=0;
    id=jTextField1.getText();
    if(jTextField1.getText().isEmpty()){
    return;
    }
             try {
                 int count=0;
                dbcon.rs = dbcon.st.executeQuery("select * from bill_record WHERE bill_record.bill_no = '"+id+"'");
               
                if (dbcon.rs.next()) { 
                    double dis=dbcon.rs.getDouble("discount"),
                   tot=dbcon.rs.getDouble("main_total");
               jTextField2.setText(dbcon.rs.getString("cusid"));
                jTextField4.setText(dbcon.rs.getString("total"));
               jLabel12.setText(dbcon.rs.getString("date"));
                jLabel25.setForeground(Color.red);
               if(dbcon.rs.getString("status").equalsIgnoreCase("Ready to Deploy"))
                jLabel25.setForeground(Color.green);
                 jLabel25.setText(dbcon.rs.getString("status"));
                jLabel13.setText(dbcon.rs.getString("delivery_date"));
                 jTextField10.setText("#"+tot);
                jTextField12.setText(String.format("%.02f",dis*100/tot)); 
                  jTextField11.setText("#"+dis);
                jTextField13.setText(dbcon.rs.getString("urgent")); 
                if(Double.parseDouble(jTextField13.getText())!=0){
                    jCheckBox1.setSelected(true);
                }
                  jTextField14.setText(dbcon.rs.getString("total"));
                 jTextField15.setText(dbcon.rs.getString("total"));
               
            }
                
             dbcon.rs = dbcon.st.executeQuery("select * from order_record WHERE bill_no = '"+id+"'");
               while (dbcon.rs.next()) { 
                count+=dbcon.rs.getInt("qty");
                jTextField16.setText(""+count); 
                int qty=dbcon.rs.getInt("qty");
                double price=dbcon.rs.getDouble("unit_price");
                Object[] data = new Object[]{++j,dbcon.rs.getString("catid"),dbcon.rs.getString("service_type"),dbcon.rs.getString("level"),price,qty,(price*qty)};
                dataSet.addRow(data);
            }
              jTable1.setModel(dataSet);
             
               dbcon.rs = dbcon.st.executeQuery("select * from update_payment WHERE bill_no = '"+id+"'");
               while (dbcon.rs.next()) { 
                advance+=dbcon.rs.getDouble("amt");
                 jTextField5.setText(""+advance); 
          jTextField17.setText(""+advance);
          jTextField6.setText(""+dbcon.rs.getDouble("balance"));
           jTextField9.setText(""+jTextField6.getText()); 
          jTextField18.setText(""+jTextField6.getText());
            }
                
            dbcon.rs = dbcon.st.executeQuery("select mobileNo from user where cusid='"+jTextField2.getText()+"'");
            if(dbcon.rs.next()){
            jTextField3.setText(dbcon.rs.getString(1));
            } else{
            JOptionPane.showMessageDialog(rootPane, "bill_no not available");
            } 
          } catch (Exception e) {
            System.out.println("get item " + e);
        }
}
}
