package laundry;

import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author damhiesax
 */
public class Expense extends javax.swing.JFrame {
DbConnect dbcon =new DbConnect();
String key="";
    DefaultComboBoxModel combomodel;
            String pro="";
            DefaultTableModel dataSet;
            DefaultTableModel dataSet2;
            int j=0;
            Double bal=0.0;
    /**
     * Creates new form Expense
     */
    public Expense() {
        initComponents();
        userID();
        jRadioButton1.setSelected(true);
        jRadioButton1ActionPerformed(null);
        getTable();
   //     System.out.println("pro "+ pro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboItemCode = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabel1.setText("VOUCHER / EXPENSE DETAILS FORM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 20, 510, 30);

        comboItemCode.setEditable(true);
        comboItemCode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        comboItemCode.setEditable(true);
        comboItemCode.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent event) {
                key=key+event.getKeyChar();

                if(event.getKeyChar()=='\b'){
                    key="";
                }
                if (!(event.getKeyChar() == KeyEvent.VK_ENTER)) {
                    System.out.println(""+event.getKeyChar());
                    getItems(key);
                }
            }
            public void keyPressed(KeyEvent event) {
                combomodel =new DefaultComboBoxModel();
                if(combomodel.getSize()==0){
                    combomodel.addElement(key);
                    comboItemCode.setModel(combomodel);
                }else{
                    combomodel.insertElementAt(key,0);
                    comboItemCode.setModel(combomodel);
                }

            }
        });
        comboItemCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboItemCodeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comboItemCodeMousePressed(evt);
            }
        });
        comboItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboItemCodeActionPerformed(evt);
            }
        });
        comboItemCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comboItemCodeKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboItemCodeKeyPressed(evt);
            }
        });
        jPanel1.add(comboItemCode);
        comboItemCode.setBounds(170, 160, 120, 20);

        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 760, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Voucher No");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 70, 110, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Date");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 100, 40, 15);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 255, 255));
        jTextField1.setEnabled(false);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(170, 70, 120, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Job Title");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 130, 90, 15);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(170, 130, 230, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Payee");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 160, 80, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Towards/Description");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 190, 150, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Process");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 250, 80, 20);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setText("Income");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(170, 250, 90, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setText("Expense");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(260, 250, 110, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Amount");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 280, 90, 15);

        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(170, 280, 230, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Cash/Cheque");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 300, 110, 15);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cash", "check" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(170, 300, 230, 21);

        jLabel12.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel12.setText("Type Keyword for Job Ttile Details");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(400, 70, 280, 18);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(410, 90, 240, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Income Total");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(450, 160, 120, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Expense Total");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(440, 190, 120, 15);

        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(570, 150, 140, 30);

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(570, 190, 140, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(170, 190, 230, 60);

        dateChooserCombo1.setCurrentView(new datechooser.view.appearance.AppearancesList("Dali",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserCombo1.setCalendarBackground(new java.awt.Color(204, 204, 255));
    dateChooserCombo1.setEnabled(false);
    dateChooserCombo1.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 11));
    dateChooserCombo1.setLocale(new java.util.Locale("en", "IE", ""));
    dateChooserCombo1.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            dateChooserCombo1OnCommit(evt);
        }
    });
    jPanel1.add(dateChooserCombo1);
    dateChooserCombo1.setBounds(170, 100, 120, 20);

    jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jPanel1.add(jLabel11);
    jLabel11.setBounds(10, 60, 760, 260);

    jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
    jButton1.setText("Export To Excel");
    jPanel1.add(jButton1);
    jButton1.setBounds(40, 340, 150, 27);

    jButton2.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
    jButton2.setText("Save");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton2);
    jButton2.setBounds(240, 340, 80, 27);

    jButton3.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
    jButton3.setText("Remove");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton3);
    jButton3.setBounds(370, 340, 110, 27);

    jButton4.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
    jButton4.setText("Close");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton4);
    jButton4.setBounds(530, 340, 80, 27);

    jLabel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jPanel1.add(jLabel15);
    jLabel15.setBounds(10, 330, 760, 50);

    jTable1 = new javax.swing.JTable(){
        public boolean isCellEditable(int row,int column){
            return false;
        }
    };
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {},
            {},
            {},
            {}
        },
        new String [] {

        }
    ));
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jPanel1.add(jScrollPane1);
    jScrollPane1.setBounds(20, 380, 730, 160);

    jLabel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jPanel1.add(jLabel16);
    jLabel16.setBounds(10, 380, 760, 170);

    jTable2 = new javax.swing.JTable(){
        public boolean isCellEditable(int row,int column){
            return false;
        }
    };
    jTable2.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {},
            {},
            {},
            {}
        },
        new String [] {

        }
    ));
    jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable2MouseClicked(evt);
        }
    });
    jScrollPane2.setViewportView(jTable2);

    jPanel1.add(jScrollPane2);
    jScrollPane2.setBounds(10, 550, 760, 120);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateChooserCombo1OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserCombo1OnCommit

    }//GEN-LAST:event_dateChooserCombo1OnCommit

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     if(jTextField2.getText().isEmpty()||comboItemCode.getSelectedItem().toString().isEmpty()||comboItemCode.getItemCount()==0||jTextField5.getText().isEmpty()){
        JOptionPane.showMessageDialog(rootPane, "Please Supply All Require Data ");
        jTextField2.requestFocus();
          return;
      }
        insert();
        getTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    int a = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to close app");
        if (a == JOptionPane.YES_OPTION) {
           this.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
    if(jRadioButton1.isSelected())
       pro="income"; 
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       if(jRadioButton2.isSelected())
       pro="expense"; 
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
     
if(jTextField5.getText().isEmpty()){
 
        return;
        } 
        Object ch = evt.getKeyChar();
            String cha = ch.toString();
             if (!"1234567890\b\n".contains(cha)) {
                jTextField5.setText(jTextField5.getText().substring(0, (jTextField5.getText().length() - 1)));
                return;
            }
                
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
            if(jTextField7.getText().isEmpty()){
            return;
        } 
        Object ch = evt.getKeyChar();
            String cha = ch.toString();
             if (!"1234567890\b\n".contains(cha)) {
                jTextField7.setText(jTextField7.getText().substring(0, (jTextField7.getText().length() - 1)));
                return;
            }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7KeyReleased

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
if(jTextField8.getText().isEmpty()){
 
        return;
        } 
        Object ch = evt.getKeyChar();
            String cha = ch.toString();
             if (!"1234567890\b\n".contains(cha)) {
                jTextField8.setText(jTextField8.getText().substring(0, (jTextField8.getText().length() - 1)));
                return;
            }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8KeyReleased

    private void comboItemCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboItemCodeKeyPressed
        //  comboItemCode.addItem(key);
    }//GEN-LAST:event_comboItemCodeKeyPressed

    private void comboItemCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboItemCodeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemCodeKeyTyped

    private void comboItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboItemCodeActionPerformed

    }//GEN-LAST:event_comboItemCodeActionPerformed

    private void comboItemCodeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboItemCodeMousePressed
        //getItem();        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemCodeMousePressed

    private void comboItemCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboItemCodeMouseClicked
        //getItem();        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemCodeMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     jTable2.setRowSelectionInterval(jTable1.getSelectedRow(),jTable1.getSelectedRow());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        delete(jTable1.getSelectedRow());
        getTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
 jTable1.setRowSelectionInterval(jTable2.getSelectedRow(),jTable2.getSelectedRow());
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Expense().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox comboItemCode;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

  public void userID() {
        try {
            int summ = 0;
            String SQLCommand2 = "select id from voucher ORDER BY id";
            dbcon.rs = dbcon.st.executeQuery(SQLCommand2);
            while (dbcon.rs.next()) {
              summ = dbcon.rs.getInt("id");
            }
           jTextField1.setText(String.valueOf("" + ++summ));
        } catch (Exception e) {
            System.out.println("Card number Error" + e);
        }
    }
  void insert(){
   try {
                dbcon.ps = dbcon.con.prepareStatement("Insert into voucher (No,date,job_title,payee,description,process,amt,means) VALUES(?,?,?,?,?,?,?,?)");
                dbcon.ps.setString(1, jTextField1.getText());
                dbcon.ps.setString(2, dateChooserCombo1.getText());
                dbcon.ps.setString(3, jTextField2.getText());
                dbcon.ps.setString(4, comboItemCode.getSelectedItem().toString());
                dbcon.ps.setString(5, jTextArea1.getText());
                dbcon.ps.setString(6, pro);
                dbcon.ps.setString(7, jTextField5.getText());
                dbcon.ps.setString(8, jComboBox1.getSelectedItem().toString());
                dbcon.ps.execute();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
  }
 public void getItems(String key) {
            combomodel =new DefaultComboBoxModel();
        try {
                dbcon.rs = dbcon.st.executeQuery("select username from loginpage WHERE username like '"+"%"+key+"%"+"'");
               
                while (dbcon.rs.next()) {  
                   combomodel.addElement(dbcon.rs.getString("username"));
              
            }
                  comboItemCode.setModel(combomodel);
                
 
        } catch (Exception e) {
            System.out.println("get item " + e);
        }
    } 
 
 void getTable(){
   j=0;
        dataSet = new DefaultTableModel();
        dataSet.addColumn("S/N");
        dataSet.addColumn("ExpID");
        dataSet.addColumn("Title");
       dataSet.addColumn("Name");
       dataSet.addColumn("Description");
        dataSet.addColumn("Income");
        dataSet.addColumn("incCheque");
         dataSet.addColumn("Expensive");
          dataSet.addColumn("expCheque");
          
            dataSet2 = new DefaultTableModel();
        dataSet2.addColumn("S/N");
        dataSet2.addColumn("Date");
        dataSet2.addColumn("openingBal");
       dataSet2.addColumn("income");
       dataSet2.addColumn("Expense");
       dataSet2.addColumn("closingBal");
        gatData();
 }
 void gatData(){
      bal=0.0;
     String process="";
     double amt=0,amt2=0;
   try {
       dbcon.rs = dbcon.st.executeQuery("select * from voucher");
        
           while (dbcon.rs.next()) { 
             process=dbcon.rs.getString("process");
             if(process.equalsIgnoreCase("income")){
             amt=dbcon.rs.getDouble("amt");
             amt2=0;
             }else{
             amt2=dbcon.rs.getDouble("amt");
             amt=0;
             }
                Object[] data = new Object[]{++j,dbcon.rs.getString("No"),dbcon.rs.getString("job_title"),dbcon.rs.getString("payee"),dbcon.rs.getString("description"),amt,dbcon.rs.getString("means"),amt2,dbcon.rs.getString("means")};
                dataSet.addRow(data);
                 Object[] data2 = new Object[]{j,dbcon.rs.getString("date"),bal,amt,amt2,bal+=(amt-amt2)};
                dataSet2.addRow(data2);
            }
                jTable1.setModel(dataSet);
                jTable2.setModel(dataSet2);
    } catch (Exception e) {
        e.printStackTrace();
    }
 }
 void  delete(int sel){
     if(sel==-1){
         JOptionPane.showMessageDialog(rootPane, "Please Select Row to Delete");
     return;
     }
     try{
            dbcon.ps = dbcon.con.prepareStatement("DELETE FROM voucher where No='" + jTable1.getValueAt(sel, 1) + "'");
            dbcon.ps.execute();
        } catch (Exception e) {
            System.out.println("red " + e.getMessage());
        }
 }
}
