package laundry;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author damhiesax
 */
public class OrderBilling extends javax.swing.JFrame {
    FormatDate fDate = new FormatDate();
   Date d;
   DefaultTableModel dataSet;
   int j;
    DbConnect dbcon = new DbConnect();
     DbConnect dbcon2 = new DbConnect();
     int position=0,del=0;
    double total,advance,balance;
     
     /**
     * Creates new form OrderBilling
     */
    public OrderBilling() {
        initComponents();
        dateChooserCombo1OnCommit(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        dateChooserCombo3 = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        dateChooserCombo1.addCommitListener(new datechooser.events.CommitListener() {
            public void onCommit(datechooser.events.CommitEvent evt) {
                dateChooserCombo1OnCommit(evt);
            }
        });
        jPanel1.add(dateChooserCombo1);
        dateChooserCombo1.setBounds(30, 140, 110, 20);

        dateChooserCombo2.addCommitListener(new datechooser.events.CommitListener() {
            public void onCommit(datechooser.events.CommitEvent evt) {
                dateChooserCombo2OnCommit(evt);
            }
        });
        jPanel1.add(dateChooserCombo2);
        dateChooserCombo2.setBounds(70, 210, 110, 20);

        dateChooserCombo3.addCommitListener(new datechooser.events.CommitListener() {
            public void onCommit(datechooser.events.CommitEvent evt) {
                dateChooserCombo3OnCommit(evt);
            }
        });
        jPanel1.add(dateChooserCombo3);
        dateChooserCombo3.setBounds(70, 250, 110, 20);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Single date"));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 120, 180, 60);

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Date Between"));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 180, 180, 100);

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton1.setText("Billing Collections");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 20, 160, 27);

        jButton2.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton2.setText("Order Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(190, 20, 130, 27);

        jButton3.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton3.setText("Undelivered Bills");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(330, 20, 180, 27);

        jButton4.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(520, 20, 100, 27);

        jButton7.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton7.setText("Billing Collections");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(10, 290, 160, 27);

        jButton8.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton8.setText("Order Details");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(10, 330, 160, 27);

        jButton9.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton9.setText("Undelivered Bills");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(10, 370, 160, 27);

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel3.setText("From");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 210, 33, 18);

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel4.setText("To");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 250, 16, 18);

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable( int rowIndex, int colIndex){
                return false;
            }
        };
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(200, 50, 730, 430);

        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(4, 100, 190, 310);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Balances");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(670, 510, 60, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Total");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(200, 510, 50, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Advances");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(420, 510, 90, 20);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(770, 500, 130, 30);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(260, 500, 130, 30);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(520, 500, 130, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(670, 0, 260, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateChooserCombo1OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserCombo1OnCommit
      
        dateChooserCombo2.setSelectedDate(dateChooserCombo1.getSelectedDate());
        dateChooserCombo3.setSelectedDate(dateChooserCombo1.getSelectedDate());
        dateChooserCombo2OnCommit(null);
    }//GEN-LAST:event_dateChooserCombo1OnCommit

    private void dateChooserCombo2OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserCombo2OnCommit
    total=0;
    advance=0;
    balance=0;
     if(position==0){
         jLabel9.setText("BILL COLLECTION");
           jTextField1.setVisible(true);
            jTextField3.setVisible(true);
            jLabel8.setVisible(true);
            jLabel6.setVisible(true);
      decision();
     }else{
            jLabel9.setText("ORDER DETAILS");
           jTextField1.setVisible(false);
            jTextField3.setVisible(false);
            jLabel8.setVisible(false);
            jLabel6.setVisible(false);
      decision1();
     }
       
           
        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserCombo2OnCommit

    private void dateChooserCombo3OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserCombo3OnCommit
        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserCombo3OnCommit

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        int a = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to close app");
        if (a == JOptionPane.YES_OPTION) {
           this.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       position=0;
        dateChooserCombo2OnCommit(null);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        position=1;
        dateChooserCombo2OnCommit(null);
        position=0;
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    jButton9ActionPerformed(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         position=0;
        dateChooserCombo2OnCommit(null);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       jButton2ActionPerformed(null); 
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
   position=0;
        del=1;
        dateChooserCombo2OnCommit(null);
         del=0;    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderBilling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderBilling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private datechooser.beans.DateChooserCombo dateChooserCombo3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
void getCollection(String date){
    
    double advance=0;
    double bal=0;
    try {
        if (del==1) {
          dbcon.rs = dbcon.st.executeQuery("select * from bill_record WHERE bill_record.date = '"+date+"' AND status=\'Not Ready to Deploy\'");
                   
        } else {
             dbcon.rs = dbcon.st.executeQuery("select * from bill_record WHERE bill_record.date = '"+date+"'");
         
        }
               
                while (dbcon.rs.next()) { 
                  dbcon2.rs = dbcon2.st.executeQuery("select * from update_payment WHERE bill_no = '"+dbcon.rs.getString("bill_no")+"'");
                    while (dbcon2.rs.next()) {                        
                      advance+=dbcon2.rs.getDouble("amt"); 
                      bal=dbcon2.rs.getDouble("balance");
                    }
                       this.advance+=advance;
                    this.balance+=bal;
                    total+= dbcon.rs.getInt("total");
              Object[] data = new Object[]{++j,dbcon.rs.getString("bill_no"),dbcon.rs.getString("cusid"),dbcon.rs.getString("main_total"),dbcon.rs.getString("discount"),dbcon.rs.getString("urgent"),dbcon.rs.getString("total"),advance,bal,dbcon.rs.getString("date"),dbcon.rs.getString("delivery_date")};
                dataSet.addRow(data);
            }
                jTable1.setModel(dataSet);
    } catch (Exception e) {
        e.printStackTrace();
    }
}
void decision(){
 j=0;
         SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
       dataSet = new DefaultTableModel();
        dataSet.addColumn("S/N");
        dataSet.addColumn("BILL_NO");
        dataSet.addColumn("CUS_ID");
        dataSet.addColumn("INT_TOTAL");
        dataSet.addColumn("DISCT");
         dataSet.addColumn("URGENCY");
          dataSet.addColumn("TOTAL");
             dataSet.addColumn("ADV");
        dataSet.addColumn("BAL");
        dataSet.addColumn("DATE");
         dataSet.addColumn("DEL_DATE");
         
         // hetre
         String startDate = fDate.getDateFormat(dateChooserCombo2.getText());
          String  stopDate = fDate.getDateFormat(dateChooserCombo3.getText());
           
            boolean chkIt = fDate.checkDate(startDate, stopDate);
            if (!chkIt) {
                JOptionPane.showMessageDialog(rootPane, "Date not properly selected\nMake sure you selected a valid date");
                return;
            }
            do {
                if (stopDate.equalsIgnoreCase(startDate)) {
                break;
                }
                d = new Date(startDate);
                getCollection(dateFormat.format(d));
                 startDate = fDate.getDate(startDate);
            } while ((!stopDate.equalsIgnoreCase(startDate)));
            d = new Date(startDate);
            getCollection(dateFormat.format(d));
            jTextField3.setText("#"+advance);
            jTextField1.setText("#"+balance);
            jTextField2.setText("#"+total);
}

//kofbnbnbfnd
void getCollection1(String date){
    double total=0;
    int qty=0;
    try {
                dbcon.rs = dbcon.st.executeQuery("select * from order_record WHERE date = '"+date+"'");
                while (dbcon.rs.next()) { 
                 qty=dbcon.rs.getInt("qty");
                 total=(qty*dbcon.rs.getDouble("unit_price"));
               Object[] data = new Object[]{++j,dbcon.rs.getString("bill_no"),dbcon.rs.getString("cusid"),dbcon.rs.getString("catid"),dbcon.rs.getString("service_type"),dbcon.rs.getString("level"),qty,total,dbcon.rs.getString("date")};
                dataSet.addRow(data);
                this.total+=total;
            }
                
                
                jTable1.setModel(dataSet);
    } catch (Exception e) {
        e.printStackTrace();
    }
}
void decision1(){
 j=0;
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
       dataSet = new DefaultTableModel();
        dataSet.addColumn("S/N");
        dataSet.addColumn("BILL_NO");
        dataSet.addColumn("CUS_ID");
        dataSet.addColumn("CAT_ID");
        dataSet.addColumn("SERV_TYPE");
         dataSet.addColumn("LEVEL");
          dataSet.addColumn("QTY");
             dataSet.addColumn("TOTAL");
         dataSet.addColumn("DATE");
        
         // hetre
         String startDate = fDate.getDateFormat(dateChooserCombo2.getText());
          String  stopDate = fDate.getDateFormat(dateChooserCombo3.getText());
           
            boolean chkIt = fDate.checkDate(startDate, stopDate);
            if (!chkIt) {
                JOptionPane.showMessageDialog(rootPane, "Date not properly selected\nMake sure you selected a valid date");
                return;
            }
            do {
                if (stopDate.equalsIgnoreCase(startDate)) {
                break;
                }
                d = new Date(startDate);
                getCollection1(dateFormat.format(d));
                 startDate = fDate.getDate(startDate);
            } while ((!stopDate.equalsIgnoreCase(startDate)));
            d = new Date(startDate);
            getCollection1(dateFormat.format(d));
            jTextField2.setText("#"+total);
}
}
