package laundry;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static laundry.Customerlist.tick;
import java.util.GregorianCalendar;
import java.text.SimpleDateFormat;

/**
 *
 * @author damhiesax
 */
public class OrderEntry extends javax.swing.JFrame {

    DbConnect dbcon = new DbConnect();
    Vector<String> data = new Vector<String>();
    Vector<String> data2 = new Vector<String>();
    Vector<String> data3 = new Vector<String>();
    Vector<String> productPrice = new Vector<String>();
    public static String[] rowData;
    public static String catID;
    String key = "",key1 = "";
    DefaultComboBoxModel combomodel1 ;
    DefaultTableModel dataSet;
    int j;
    Double qty=0.0;
    Date d;;
    Double total=0.0;
    Double discount=0.0;
    Double initTotal=0.0;
    int force=0;
    int id=0;
    FormatDate fDate = new FormatDate();
    /**
     * Creates new form OrderEntry
     */
    public OrderEntry() {
         dataSet = new DefaultTableModel();
        dataSet.addColumn("S/N");
        dataSet.addColumn("CATEGORY");
        dataSet.addColumn("ITEM");
        dataSet.addColumn("LEVEL");
        dataSet.addColumn("RATE");
         dataSet.addColumn("QTY");
          dataSet.addColumn("TOTAL");
        initComponents();
        setTitle("ORDER ENTRY");
         getItems("");
         fillcombo2();
       jTextField10.setText(""+getId());
       jTextField9.setEditable(false);
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
       
        String dd=dateChooserCombo1.getText();
        System.out.println(dd);
      
        dd=fDate.getDateFormat(dd);
        d=new Date(dd);
       jLabel8.setText(dateFormat.format(d)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel31 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        comboItemCode1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setText("New Order Entry");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 10, 200, 24);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("To Modify Bill-No");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(420, 20, 120, 14);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(530, 10, 110, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(650, 10, 80, 30);

        jLabel32.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jPanel1.add(jLabel32);
        jLabel32.setBounds(740, 14, 80, 20);

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 830, 50);

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel4.setText("Customer ID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 60, 110, 18);

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel6.setText("Garment Type");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(390, 60, 130, 18);

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel7.setText("Starch Level");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(590, 60, 140, 18);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Price");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(390, 150, 40, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Quantity");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(490, 150, 70, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Total");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(590, 150, 70, 15);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField7);
        jTextField7.setBounds(380, 170, 100, 30);

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(490, 170, 90, 30);

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField9MouseClicked(evt);
            }
        });
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField9KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField9);
        jTextField9.setBounds(590, 170, 110, 30);

        jButton2.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(710, 170, 90, 27);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Advance");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(70, 320, 80, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Transaction No");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 200, 130, 15);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Bill Date");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(70, 240, 60, 15);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Bill Amount");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(60, 280, 80, 15);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Bill Balance");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(60, 360, 100, 15);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Tenderred Amount");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(0, 400, 140, 15);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Delivery Date");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(40, 530, 100, 15);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Tenderred Balance");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(0, 440, 140, 15);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Final Bill Balance");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(20, 480, 120, 15);

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.add(jTextField10);
        jTextField10.setBounds(140, 200, 150, 30);

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(0, 204, 153));
        jTextField11.setText("0");
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField11KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField11);
        jTextField11.setBounds(140, 280, 150, 30);

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(0, 204, 153));
        jTextField12.setText("0");
        jTextField12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField12MouseClicked(evt);
            }
        });
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField12KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField12);
        jTextField12.setBounds(140, 320, 150, 30);

        jTextField13.setEditable(false);
        jTextField13.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.add(jTextField13);
        jTextField13.setBounds(140, 360, 150, 30);

        jTextField14.setEditable(false);
        jTextField14.setBackground(new java.awt.Color(0, 204, 153));
        jTextField14.setText("0");
        jPanel1.add(jTextField14);
        jTextField14.setBounds(140, 400, 150, 30);

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(0, 204, 153));
        jTextField15.setText("0");
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField15);
        jTextField15.setBounds(140, 440, 150, 30);

        jTextField16.setEditable(false);
        jTextField16.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.add(jTextField16);
        jTextField16.setBounds(140, 480, 150, 30);

        jButton3.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton3.setText("save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(80, 580, 90, 27);

        jButton4.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton4.setText("Print");
        jPanel1.add(jButton4);
        jButton4.setBounds(190, 580, 80, 27);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Remove");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(390, 370, 100, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Sub Total");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(580, 370, 70, 15);

        jTextField17.setEditable(false);
        jTextField17.setBackground(new java.awt.Color(204, 204, 255));
        jTextField17.setText("0");
        jTextField17.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), null));
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField17);
        jTextField17.setBounds(760, 360, 60, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Discount");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(580, 400, 70, 15);

        jTextField18.setText("0");
        jTextField18.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), null));
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jTextField18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField18KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField18KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField18);
        jTextField18.setBounds(670, 400, 60, 20);

        jTextField19.setText("0");
        jTextField19.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), null));
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jTextField19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField19KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField19);
        jTextField19.setBounds(760, 390, 60, 30);

        jTextField20.setText("0");
        jTextField20.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), null));
        jTextField20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField20KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField20);
        jTextField20.setBounds(760, 420, 60, 30);

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBox1.setText("URGENT");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(670, 430, 73, 23);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Bill No");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(390, 420, 60, 15);

        jTextField21.setEditable(false);
        jTextField21.setBackground(new java.awt.Color(204, 204, 255));
        jTextField21.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), null));
        jPanel1.add(jTextField21);
        jTextField21.setBounds(390, 440, 110, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Re-Print");
        jPanel1.add(jButton6);
        jButton6.setBounds(390, 480, 110, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Total");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(590, 470, 40, 15);

        jTextField22.setEditable(false);
        jTextField22.setBackground(new java.awt.Color(204, 204, 255));
        jTextField22.setText("0");
        jTextField22.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), null));
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField22);
        jTextField22.setBounds(760, 460, 60, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Net Total");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(590, 510, 70, 15);

        jTextField23.setEditable(false);
        jTextField23.setBackground(new java.awt.Color(204, 204, 255));
        jTextField23.setText("0");
        jTextField23.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), null));
        jPanel1.add(jTextField23);
        jTextField23.setBounds(760, 500, 60, 30);

        jTextField24.setEditable(false);
        jTextField24.setBackground(new java.awt.Color(255, 255, 255));
        jTextField24.setText("0");
        jTextField24.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), null));
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField24);
        jTextField24.setBounds(680, 500, 60, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Advance");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(680, 550, 70, 15);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Balance");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(680, 590, 60, 15);

        jTextField25.setText("0");
        jTextField25.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), null));
        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });
        jTextField25.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField25KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField25);
        jTextField25.setBounds(760, 540, 60, 30);

        jTextField26.setEditable(false);
        jTextField26.setBackground(new java.awt.Color(204, 204, 255));
        jTextField26.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), null));
        jPanel1.add(jTextField26);
        jTextField26.setBounds(760, 580, 60, 30);

        jButton7.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton7.setText("Close");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(400, 580, 80, 27);

        jLabel28.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel1.add(jLabel28);
        jLabel28.setBounds(380, 360, 450, 260);

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable( int rowIndex, int colIndex){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(380, 210, 452, 150);

        jLabel30.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel1.add(jLabel30);
        jLabel30.setBounds(370, 140, 470, 490);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(140, 520, 120, 30);

        dateChooserCombo1.setLocale(new java.util.Locale("en", "GB", ""));
        dateChooserCombo1.addCommitListener(new datechooser.events.CommitListener() {
            public void onCommit(datechooser.events.CommitEvent evt) {
                dateChooserCombo1OnCommit(evt);
            }
        });
        jPanel1.add(dateChooserCombo1);
        dateChooserCombo1.setBounds(270, 530, 20, 20);

        jLabel31.setBackground(new java.awt.Color(204, 204, 204));
        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(jLabel31);
        jLabel31.setBounds(140, 240, 150, 30);

        jLabel29.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel1.add(jLabel29);
        jLabel29.setBounds(10, 140, 370, 490);

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel5.setText("Category");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 60, 80, 18);

        jComboBox2.setEnabled(false);
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeVisible(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(220, 80, 150, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HIGH", "LOW", "MEDIUM" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(590, 80, 160, 20);

        jComboBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox4MouseExited(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox4);
        jComboBox4.setBounds(390, 80, 170, 20);

        comboItemCode1.setEditable(true);
        comboItemCode1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        comboItemCode1.setEditable(true);
        comboItemCode1.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent event) {
                key1=key1+event.getKeyChar();

                if(event.getKeyChar()=='\b'){
                    key1="";
                }
                if (!(event.getKeyChar() == KeyEvent.VK_ENTER)) {
                    System.out.println(""+event.getKeyChar());
                    getItems(key1);
                }else{
                    if(!comboItemCode1.getSelectedItem().toString().isEmpty())
                    jComboBox2.setEnabled(true);
                }
            }
            public void keyPressed(KeyEvent event) {
                combomodel1 =new DefaultComboBoxModel();
                if(combomodel1.getSize()==0){
                    combomodel1.addElement(key1);
                    comboItemCode1.setModel(combomodel1);
                }else{
                    combomodel1.insertElementAt(key1,0);
                    comboItemCode1.setModel(combomodel1);
                }

            }
        });
        comboItemCode1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comboItemCode1MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboItemCode1MouseClicked(evt);
            }
        });
        comboItemCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboItemCode1ActionPerformed(evt);
            }
        });
        comboItemCode1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comboItemCode1KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboItemCode1KeyPressed(evt);
            }
        });
        jPanel1.add(comboItemCode1);
        comboItemCode1.setBounds(10, 80, 190, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9KeyReleased

    private void jTextField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseClicked
        float num1, num2, result;
        num1 = Float.parseFloat(jTextField7.getText());
        num2 = Float.parseFloat(jTextField8.getText());
        result = num1 * num2;
        jTextField9.setText(String.valueOf("#" + result));

// TODO add your handling code here:
    }//GEN-LAST:event_jTextField9MouseClicked

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
         Object ch = evt.getKeyChar();
            String cha = ch.toString();
                 if (!"1234567890\b\n".contains(cha)) {
                jTextField8.setText(jTextField8.getText().substring(0, (jTextField8.getText().length() - 1)));
                return;
            }
        
        if(!jTextField8.getText().isEmpty()){
        float num1, num2, result;
        num1 = Float.parseFloat(jTextField7.getText());
        num2 = Float.parseFloat(jTextField8.getText());
        result = num1 * num2;
        jTextField9.setText(String.valueOf("#" + result));
}
        

// TODO add your handling code here:
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            if(jTextField8.getText().isEmpty()||jTextField7.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Specify the no Qty or Price");
            return;
            }
        fillTable();
        clear();
       SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
        d=new Date();
        d=new Date(d.getTime());
       jLabel31.setText(dateFormat.format(d));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField12MouseClicked
        jTextField12.setText("#");
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12MouseClicked

    private void jTextField11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyReleased
        jTextField12.setText("#");
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11KeyReleased

    private void jTextField12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyReleased
        jTextField12.setText("#");
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12KeyReleased

    private void jComboBox2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeInvisible

    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
        //displayprice();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7MouseClicked

    private void jComboBox2PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeVisible
// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeVisible

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        fillcombo();
        clear();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        displayprice();        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4MouseExited

    private void comboItemCode1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboItemCode1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemCode1MouseClicked

    private void comboItemCode1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboItemCode1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemCode1MousePressed

    private void comboItemCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboItemCode1ActionPerformed
        //      if(comboItemCode1.isFocusOwner()){
            //      if(comboItemCode1.getItemCount() >0){
             jComboBox2.setEnabled(true);
                //      }
            //      }
    }//GEN-LAST:event_comboItemCode1ActionPerformed

    private void comboItemCode1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboItemCode1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemCode1KeyPressed

    private void comboItemCode1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboItemCode1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemCode1KeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     
        removeGame(jTable1.getSelectedRow());  // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField18KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField18KeyReleased
       
        if(jTextField18.getText().isEmpty()){
        return;
        } 
            String cha="";
            if(force!=1){
            Object ch = evt.getKeyChar();
            cha = ch.toString();
            force=0;
            }
            int dot=0;
            for (int i = 0; i < jTextField18.getText().length(); i++) {
            String chk=jTextField18.getText().substring(i,i+1);
            if(chk.equals(".")){
            dot++;
            }if (!".1234567890\b\n".contains(cha) || dot>1) {
                jTextField18.setText(jTextField18.getText().substring(0, (jTextField18.getText().length() - 1)));
                return;
             }
             }
             
              jTextField19.setText(""+(Double.parseDouble(jTextField18.getText())*0.01*Double.parseDouble(jTextField17.getText())));  
              force=1;
           jTextField19KeyReleased(null);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18KeyReleased

    private void jTextField19KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField19KeyReleased
        if(jTextField19.getText().isEmpty()){
        return;
        }   
        if(force!=1){
        Object ch = evt.getKeyChar();
            String cha = ch.toString();
             if (!"1234567890\b\n".contains(cha)) {
                jTextField19.setText(jTextField19.getText().substring(0, (jTextField19.getText().length() - 1)));
                return;
            }
             force=0;
        }
            
             if(jCheckBox1.isSelected()){
              initTotal=Double.parseDouble(jTextField17.getText())-(Double.parseDouble(jTextField19.getText()))+(Double.parseDouble(jTextField20.getText()));
             }else{
              initTotal=Double.parseDouble(jTextField17.getText())-(Double.parseDouble(jTextField19.getText()));
             }
            jTextField23.setText(String.format("%.02f", initTotal));
             jTextField22.setText(String.format("%.02f", initTotal));
             jTextField11.setText(String.format("%.02f", initTotal));
             jTextField26.setText(String.format("%.02f", Double.parseDouble(jTextField22.getText())-Double.parseDouble(jTextField25.getText())));
             jTextField13.setText(jTextField26.getText());
    }//GEN-LAST:event_jTextField19KeyReleased

    private void jTextField20KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField20KeyReleased
        if(jTextField20.getText().isEmpty()){
        return;
        }    
        if(force !=1){
         Object ch = evt.getKeyChar();
            String cha = ch.toString();
             if (!"1234567890\b\n".contains(cha)) {
                jTextField20.setText(jTextField20.getText().substring(0, (jTextField20.getText().length() - 1)));
                return;
            }
             force=0;
        }
             
           if(jCheckBox1.isSelected()){
              initTotal=Double.parseDouble(jTextField17.getText())-(Double.parseDouble(jTextField19.getText()))+(Double.parseDouble(jTextField20.getText()));
             }else{
              initTotal=Double.parseDouble(jTextField17.getText())-(Double.parseDouble(jTextField19.getText()));
             }
             jTextField23.setText(String.format("%.02f", initTotal));
             jTextField11.setText(String.format("%.02f", initTotal));
             jTextField22.setText(String.format("%.02f", initTotal));
            jTextField26.setText(String.format("%.02f", Double.parseDouble(jTextField22.getText())-Double.parseDouble(jTextField25.getText())));
             jTextField13.setText(jTextField26.getText());  
             // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20KeyReleased

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void jTextField25KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField25KeyReleased
         if(jTextField25.getText().isEmpty()){
        return;
        } 
        Object ch = evt.getKeyChar();
            String cha = ch.toString();
             if (!"1234567890\b\n".contains(cha)) {
                jTextField25.setText(jTextField25.getText().substring(0, (jTextField25.getText().length() - 1)));
                return;
            }
            jTextField12.setText(jTextField25.getText()); 
         jTextField26.setText(String.format("%.02f", Double.parseDouble(jTextField22.getText())-Double.parseDouble(jTextField25.getText())));
           jTextField13.setText(jTextField26.getText());  
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25KeyReleased

    private void jTextField18KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField18KeyPressed
           // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18KeyPressed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       force=1;
        jTextField20KeyReleased(null);       
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
   int a = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to close app");
        if (a == JOptionPane.YES_OPTION) {
           this.setVisible(false);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            jLabel32.setText("available");
        try {
                dbcon.rs = dbcon.st.executeQuery("select id from bill_record Order by id");
              while (dbcon.rs.next()) {  
              id=dbcon.rs.getInt("id");
              if(Integer.parseInt(jTextField1.getText())==id){
              jLabel32.setText("unavailable");
              }
           }
              if(jLabel32.getText().equalsIgnoreCase("available")){
              id=Integer.parseInt(jTextField1.getText());
              jTextField10.setText(""+id);
               jTextField21.setText(""+id);
              }
            } catch (Exception e) {
            System.out.println("get id " + e);
        }      
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      dropToDb();
      jTextField10.setText(""+getId());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void dateChooserCombo1OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserCombo1OnCommit
      SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
        String dd=dateChooserCombo1.getText();
        dd=fDate.getDateFormat(dd);
        d=new Date(dd);
       jLabel8.setText(dateFormat.format(d));      
    }//GEN-LAST:event_dateChooserCombo1OnCommit

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboItemCode1;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private void fillcombo() {
         combomodel1 =new DefaultComboBoxModel();
        try {
            String SQLCommand = "select productName from item where productCat='"+jComboBox2.getSelectedItem().toString()+"'";
            dbcon.rs = dbcon.st.executeQuery(SQLCommand);
            while (dbcon.rs.next()) {
                String productName = dbcon.rs.getString("productName");
               combomodel1.addElement(productName);

            }
            jComboBox4.setModel(combomodel1);
        } catch (Exception e) {
        }

    }

    private void fillcombo2() {
          combomodel1 =new DefaultComboBoxModel();
       String ch="" ;
        String productCat;
        try {
            String SQLCommand = "select productCat from item";
            dbcon.rs = dbcon.st.executeQuery(SQLCommand);
            while (dbcon.rs.next()) {
               productCat = dbcon.rs.getString("productCat");
               if(!ch.contains(productCat)){
                 combomodel1.addElement(productCat);
                ch=ch.concat(productCat);
               }
            }
            jComboBox2.setModel(combomodel1);
        } catch (Exception e) {
        }
    }

    void displayprice() {
        String conf = jComboBox4.getSelectedItem().toString();
        String man = jComboBox2.getSelectedItem().toString();
        System.out.println("test here  " + conf + "   222   " + man);
        try {

            dbcon.rs = dbcon.st.executeQuery(" select productPrice from item where productCat='" + man + "' AND productName='" + conf + "'");
            dbcon.rs.next();
            String add = dbcon.rs.getString("productPrice");
            System.out.println("price is " + add);
            jTextField7.setText(add);

        } catch (Exception g) {
            System.out.print("there is error" + g);
        }
    }

    void clear() {
        jTextField7.setText(null);
        jTextField8.setText(null);
        jTextField9.setText(null);
    }
    public void getItems(String key1) {
           combomodel1 =new DefaultComboBoxModel();
       
            try {
                dbcon.rs = dbcon.st.executeQuery("select * from user WHERE cusid like '"+"%"+key1+"%"+"'");
               
                while (dbcon.rs.next()) {  
                String id=dbcon.rs.getString("cusid");
                combomodel1.addElement(id);
            }
           comboItemCode1.setModel(combomodel1);
          } catch (Exception e) {
            System.out.println("get item " + e);
        }
    }
       void fillTable(){
           force=1;
        if(validateRowToTable()){
            if(!jTextField18.getText().isEmpty()){
                    jTextField18KeyReleased(null);
                    }else{
                     jTextField19KeyReleased(null);
                    }
        return;
        }
           
           
      Object[] data = new Object[]{++j,jComboBox2.getSelectedItem().toString(),jComboBox4.getSelectedItem().toString(),jComboBox3.getSelectedItem().toString(),jTextField7.getText(),jTextField8.getText(),jTextField9.getText()};
       dataSet.addRow(data);
                    total+=Double.parseDouble(jTextField9.getText().replace("#", ""));
                    qty+=Double.parseDouble(jTextField8.getText());
                    jTextField11.setText(String.format("%.02f", total));
                    jTextField13.setText(String.format("%.02f", total));
                     jTextField16.setText(String.format("%.02f", total));
                     jTextField26.setText(String.format("%.02f", total));
                     jTextField23.setText(String.format("%.02f", total));
                     jTextField22.setText(String.format("%.02f", total));
                    jTextField17.setText(String.format("%.02f", total));
                    jTextField24.setText(String.format("%.00f", qty));
                    jTable1.setModel(dataSet);
                    
                 if(!jTextField18.getText().isEmpty()){
                    jTextField18KeyReleased(null);
                    }else{
                     jTextField19KeyReleased(null);
                    }
       }
       
       void removeGame(int sel) {
               total=0.0;
               qty=0.0;
        try {
            if (sel == -1) {
                JOptionPane.showMessageDialog(rootPane, "Select Row to Remove");
            return;
            }
                dataSet.removeRow(sel);
                jTable1.setModel(dataSet);
                j = dataSet.getRowCount();

                //System.out.println("hreregfdggfdgc");
                for (int k = 0; k < j; k++) {
                   dataSet.setValueAt(k+1, k, 0);
                    total+=Double.parseDouble(jTable1.getValueAt(k, 6).toString().replace("#",""));
                    qty+=Double.parseDouble(jTable1.getValueAt(k, 5).toString());
                    }
                    jTextField11.setText(String.format("%.02f", total));
                    jTextField13.setText(String.format("%.02f", total));
                     jTextField16.setText(String.format("%.02f", total));
                     jTextField26.setText(String.format("%.02f", total));
                     jTextField23.setText(String.format("%.02f", total));
                     jTextField22.setText(String.format("%.02f", total));
                    jTextField17.setText(String.format("%.02f", total));
                    jTextField24.setText(String.format("%.00f", qty));
                     force=1;
                    if(!jTextField18.getText().isEmpty()){
                    jTextField18KeyReleased(null);
                    }else{
                     jTextField19KeyReleased(null);
                    }
                    
                jTable1.setModel(dataSet);
                jTable1.repaint();
                JOptionPane.showMessageDialog(rootPane, "Item Removed successfully");
                 } catch (Exception e) {
            e.printStackTrace();
        }
    }
        void dropToDb(){
            if(comboItemCode1.getSelectedItem().toString().isEmpty()||jTable1.getRowCount()==0){
              JOptionPane.showMessageDialog(rootPane, "No Item to Post\nOr invalid Customer ID");
              return;
            }
            try {
                //into bill
                  dbcon.ps = dbcon.con.prepareStatement("insert into bill_record (bill_no,main_total,discount,urgent,total,advance,balance,date,delivery_date,cusid) values (?,?,?,?,?,?,?,?,?,?)");
                    if(jTextField21.getText().isEmpty()){
                    dbcon.ps.setString(1, ""+id);
                    }else{
                     dbcon.ps.setString(1, "m"+id);
                    }
                     dbcon.ps.setString(2, jTextField17.getText());
                    dbcon.ps.setString(3, jTextField19.getText());
                    dbcon.ps.setString(4, jTextField20.getText()); 
                    dbcon.ps.setString(5, jTextField22.getText());
                    dbcon.ps.setString(6, jTextField25.getText());
                    dbcon.ps.setString(7, jTextField26.getText());
                    dbcon.ps.setString(8, jLabel31.getText());
                    dbcon.ps.setString(9, jLabel8.getText());
                    dbcon.ps.setString(10, comboItemCode1.getSelectedItem().toString());
                    dbcon.ps.execute();
                    
                    //into order
                    for (int i = 0; i < jTable1.getRowCount(); i++) {
            try {
                dbcon.ps = dbcon.con.prepareStatement("Insert into order_record (cusid,catid,service_type,level,unit_price,qty,bill_no,date) VALUES(?,?,?,?,?,?,?,?)");
                dbcon.ps.setString(1, comboItemCode1.getSelectedItem().toString());
                dbcon.ps.setString(2, jTable1.getValueAt(i, 1).toString());
                dbcon.ps.setString(3, jTable1.getValueAt(i, 2).toString());
                dbcon.ps.setString(4, jTable1.getValueAt(i, 3).toString());
                dbcon.ps.setString(5, jTable1.getValueAt(i, 4).toString());
                dbcon.ps.setString(6, jTable1.getValueAt(i, 5).toString());
                dbcon.ps.setString(7, jTextField10.getText());
                dbcon.ps.setString(8, jLabel31.getText());
                dbcon.ps.execute();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
           }
                    
            try {
                dbcon.ps = dbcon.con.prepareStatement("Insert into update_payment (bill_no,amt,balance,date) VALUES(?,?,?,?)");
                dbcon.ps.setString(1, jTextField10.getText());
                dbcon.ps.setString(2, jTextField25.getText());
                dbcon.ps.setString(3, jTextField26.getText());
                dbcon.ps.setString(4, jLabel31.getText());
 
                dbcon.ps.execute();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        
                   JOptionPane.showMessageDialog(rootPane, "ITEM SAVED");
                   this.dispose();
                    new OrderEntry().setVisible(true);
            } catch (Exception e) {
                e.printStackTrace();
            }
    }
        int getId(){
        try {
                dbcon.rs = dbcon.st.executeQuery("select id from bill_record Order by id");
              while (dbcon.rs.next()) {  
              id=dbcon.rs.getInt("id");
           }
            } catch (Exception e) {
            System.out.println("get id " + e);
        } 
        return ++id;
        }
    public boolean validateRowToTable() {
        boolean status=false;
        int l = jTable1.getRowCount();
        for (int j = 0; j < dataSet.getRowCount(); j++) {
            if ((jComboBox2.getSelectedItem().toString().equalsIgnoreCase(dataSet.getValueAt(j, 1).toString())
                    && (jComboBox4.getSelectedItem().toString().equalsIgnoreCase(dataSet.getValueAt(j, 2).toString()))
                    && (jComboBox3.getSelectedItem().toString().equalsIgnoreCase(dataSet.getValueAt(j, 3).toString())))) {
                status=true;
               int a = JOptionPane.showConfirmDialog(rootPane, "Item Existed Already \nTo add to available item click YES");
                     if (a == JOptionPane.YES_OPTION) {
                         dataSet.setValueAt(Integer.parseInt(jTable1.getValueAt(j, 5).toString())+Integer.parseInt(jTextField8.getText()), j, 5);
                         dataSet.setValueAt("#"+(Integer.parseInt(dataSet.getValueAt(j, 5).toString())*Double.parseDouble(jTextField7.getText())), j, 6);
                            total+=Double.parseDouble(jTextField9.getText().replace("#", ""));
                    qty+=Double.parseDouble(jTextField8.getText());
                    jTextField11.setText(String.format("%.02f", total));
                    jTextField13.setText(String.format("%.02f", total));
                     jTextField16.setText(String.format("%.02f", total));
                     jTextField26.setText(String.format("%.02f", total));
                     jTextField23.setText(String.format("%.02f", total));
                     jTextField22.setText(String.format("%.02f", total));
                    jTextField17.setText(String.format("%.02f", total));
                    jTextField24.setText(String.format("%.00f", qty));
                         jTable1.setModel(dataSet);
                     }
            }
        }
        return status;
    }   
   
}
