package laundry;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author damhiesax
 */
public class searchBills extends javax.swing.JFrame {
  DbConnect dbcon = new DbConnect();
    DbConnect dbcon2 = new DbConnect();
    String key = "",key1="";
    DefaultComboBoxModel combomodel;
    DefaultTableModel dataSet;
    int j=0;
    Vector<String> data;
    FormatDate fDate = new FormatDate();
   Date d;
   int force=0;
    /**
     * Creates new form searchBills
     */
    public searchBills() {
        initComponents();
        status();
        jComboBox2.setModel(combomodel);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboItemCode = new javax.swing.JComboBox();
        comboItemCode1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("Customer ID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 70, 14);

        comboItemCode.setEditable(true);
        comboItemCode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        comboItemCode.setEditable(true);
        comboItemCode.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent event) {
                key=key+event.getKeyChar();

                if(event.getKeyChar()=='\b'){
                    key="";
                }
                if (!(event.getKeyChar() == KeyEvent.VK_ENTER)) {
                    System.out.println(""+event.getKeyChar());
                    getItems(key);
                }else{
                    getItem(comboItemCode.getSelectedItem().toString());
                }
            }
            public void keyPressed(KeyEvent event) {
                combomodel =new DefaultComboBoxModel();
                if(combomodel.getSize()==0){
                    combomodel.addElement(key);
                    comboItemCode.setModel(combomodel);
                }else{
                    combomodel.insertElementAt(key,0);
                    comboItemCode.setModel(combomodel);
                }

            }
        });
        comboItemCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboItemCodeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comboItemCodeMousePressed(evt);
            }
        });
        comboItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboItemCodeActionPerformed(evt);
            }
        });
        comboItemCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboItemCodeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comboItemCodeKeyTyped(evt);
            }
        });
        jPanel1.add(comboItemCode);
        comboItemCode.setBounds(90, 20, 120, 20);

        comboItemCode1.setEditable(true);
        comboItemCode1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        comboItemCode1.setEditable(true);
        comboItemCode1.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent event) {
                key1=key1+event.getKeyChar();

                if(event.getKeyChar()=='\b'){
                    key1="";
                }
                if (!(event.getKeyChar() == KeyEvent.VK_ENTER)) {
                    System.out.println(""+event.getKeyChar());
                    getMobile(key1);
                }else{
                    getMobileItems(comboItemCode1.getSelectedItem().toString());
                }
            }
            public void keyPressed(KeyEvent event) {
                combomodel =new DefaultComboBoxModel();
                if(combomodel.getSize()==0){
                    combomodel.addElement(key);
                    comboItemCode1.setModel(combomodel);
                }else{
                    combomodel.insertElementAt(key,0);
                    comboItemCode1.setModel(combomodel);
                }

            }
        });
        comboItemCode1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboItemCode1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comboItemCode1MousePressed(evt);
            }
        });
        comboItemCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboItemCode1ActionPerformed(evt);
            }
        });
        comboItemCode1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboItemCode1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comboItemCode1KeyTyped(evt);
            }
        });
        jPanel1.add(comboItemCode1);
        comboItemCode1.setBounds(520, 20, 120, 20);

        jButton1.setText("Amount Pending");
        jPanel1.add(jButton1);
        jButton1.setBounds(230, 20, 130, 23);

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 10, 370, 50);

        jLabel3.setText("Bill No");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 90, 60, 14);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(80, 90, 160, 20);

        jLabel4.setText("Status");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 90, 50, 14);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(320, 90, 120, 20);

        jButton2.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(330, 120, 90, 27);

        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 80, 210, 70);

        jLabel6.setText("Mobile No");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(470, 20, 80, 14);

        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(780, 20, 70, 23);

        jLabel7.setText("Bill Date");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(470, 70, 60, 14);

        jLabel8.setText("Start Bill No");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(470, 130, 90, 14);

        jLabel9.setText("End Billl No");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(470, 170, 90, 14);

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(560, 130, 110, 20);

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(560, 170, 110, 20);

        jButton6.setText("Amount Pending");
        jPanel1.add(jButton6);
        jButton6.setBounds(670, 170, 130, 23);

        jButton7.setText("All Bills");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(800, 170, 70, 23);

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 260, 880, 250);

        jButton8.setText("Export To Excel");
        jPanel1.add(jButton8);
        jButton8.setBounds(730, 230, 130, 23);

        dateChooserCombo1.addCommitListener(new datechooser.events.CommitListener() {
            public void onCommit(datechooser.events.CommitEvent evt) {
                dateChooserCombo1OnCommit(evt);
            }
        });
        jPanel1.add(dateChooserCombo1);
        dateChooserCombo1.setBounds(530, 70, 110, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboItemCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboItemCodeMouseClicked
        //getItem();        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemCodeMouseClicked

    private void comboItemCodeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboItemCodeMousePressed
        //getItem();        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemCodeMousePressed

    private void comboItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboItemCodeActionPerformed
         getItem(comboItemCode.getSelectedItem().toString());
    }//GEN-LAST:event_comboItemCodeActionPerformed

    private void comboItemCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboItemCodeKeyPressed
        //  comboItemCode.addItem(key);
    }//GEN-LAST:event_comboItemCodeKeyPressed

    private void comboItemCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboItemCodeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemCodeKeyTyped

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
     
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  if(jComboBox2.getSelectedIndex()==2)
      return;
        update();
     jComboBox1ActionPerformed(null);   
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        j=0;
        dataSet = new DefaultTableModel();
        dataSet.addColumn("S/N");
        dataSet.addColumn("BILL_NO");
        dataSet.addColumn("CUS_ID");
        dataSet.addColumn("TOTAL");
        dataSet.addColumn("ADV");
        dataSet.addColumn("BAL");
        dataSet.addColumn("DATE");
         dataSet.addColumn("DELIVERY_DATE");
          dataSet.addColumn("STATUS");
        getTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void comboItemCode1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboItemCode1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemCode1MouseClicked

    private void comboItemCode1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboItemCode1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemCode1MousePressed

    private void comboItemCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboItemCode1ActionPerformed
       getMobileItems(data.elementAt(comboItemCode1.getSelectedIndex()));
        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemCode1ActionPerformed

    private void comboItemCode1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboItemCode1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemCode1KeyPressed

    private void comboItemCode1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboItemCode1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemCode1KeyTyped

    private void dateChooserCombo1OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserCombo1OnCommit
       force=1;
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
        String dd=dateChooserCombo1.getText();
        dd=fDate.getDateFormat(dd);
        d=new Date(dd);
         getItemOnDate(dateFormat.format(d));
        force=0;
    }//GEN-LAST:event_dateChooserCombo1OnCommit

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      
        int a = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to close app");
        if (a == JOptionPane.YES_OPTION) {
          this.setVisible(false);
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       getBill();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
          if(jTextField3.getText().isEmpty()){
              combomodel=new DefaultComboBoxModel();
              jComboBox1.setModel(combomodel);
        return;
        } 
        Object ch = evt.getKeyChar();
            String cha = ch.toString();
          
        if (!"1234567890\b\n".contains(cha)) {
                jTextField3.setText(jTextField3.getText().substring(0, (jTextField3.getText().length() - 1)));
                return;
             }
         if(jTextField4.getText().isEmpty() ||jTextField3.getText().isEmpty()){
        return;
        }
        
        if(Integer.parseInt(jTextField4.getText())<Integer.parseInt(jTextField3.getText())){
            JOptionPane.showMessageDialog(rootPane, "Invalid Rage");
            return;
        }
        getBill(Integer.parseInt(jTextField3.getText()),Integer.parseInt(jTextField4.getText()));
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        if(jTextField4.getText().isEmpty()){
             combomodel=new DefaultComboBoxModel();
              jComboBox1.setModel(combomodel);
        return;
        }
        Object ch = evt.getKeyChar();
            String cha = ch.toString();
        if (!"1234567890\b\n".contains(cha)) {
                jTextField4.setText(jTextField4.getText().substring(0, (jTextField4.getText().length() - 1)));
                return;
          }
        
        if(jTextField4.getText().isEmpty()||jTextField3.getText().isEmpty()){
        return;
        }
        if(Integer.parseInt(jTextField4.getText())<Integer.parseInt(jTextField3.getText())){
            JOptionPane.showMessageDialog(rootPane, "Invalid Rage");
            return;
        }
        getBill(Integer.parseInt(jTextField3.getText()),Integer.parseInt(jTextField4.getText()));
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchBills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboItemCode;
    private javax.swing.JComboBox comboItemCode1;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
public void getItem(String item) {
       combomodel =new DefaultComboBoxModel();
        try {
          dbcon.rs = dbcon.st.executeQuery("select * from bill_record WHERE cusid = '"+item+"'");
            while (dbcon.rs.next()) {                
                 combomodel.addElement(dbcon.rs.getString("bill_no"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        jComboBox1.setModel(combomodel);
     }

   public void getItems(String key) {
            combomodel =new DefaultComboBoxModel();
        try {
                dbcon.rs = dbcon.st.executeQuery("select cusid from user WHERE cusid like '"+"%"+key+"%"+"'");
               
                while (dbcon.rs.next()) {  
                   combomodel.addElement(dbcon.rs.getString("cusid"));
              
            }
                  comboItemCode.setModel(combomodel);
                
 
        } catch (Exception e) {
            System.out.println("get item " + e);
        }
    }
    void status(){
     combomodel =new DefaultComboBoxModel();
     combomodel.addElement("-Select-");
     combomodel.addElement("Ready to Deploy");
     combomodel.addElement("Not Ready to Deploy");
    }
     private void update() {
        try {

            dbcon.ps = dbcon.con.prepareStatement("update bill_record set status='"+jComboBox2.getSelectedItem().toString()+"' where cusid='"+comboItemCode.getSelectedItem().toString()+"' and  bill_no='"+jComboBox1.getSelectedItem().toString()+"'");
            dbcon.ps.executeUpdate();
        } catch (Exception e) {
            System.out.println("red " + e.getMessage());
        }
    }
     void getTable(){
         double advance=0,bal=0;
       try {
              
                 dbcon.rs = dbcon.st.executeQuery("select * from bill_record WHERE bill_record.bill_no = '"+jComboBox1.getSelectedItem().toString()+"'");
               
                while (dbcon.rs.next()) { 
                  dbcon2.rs = dbcon2.st.executeQuery("select * from update_payment WHERE bill_no = '"+dbcon.rs.getDouble("bill_no")+"'");
                    while (dbcon2.rs.next()) {                        
                      advance+=dbcon2.rs.getDouble("amt"); 
                      bal=dbcon2.rs.getDouble("balance");
                    }
              Object[] data = new Object[]{++j,dbcon.rs.getString("bill_no"),dbcon.rs.getString("cusid"),dbcon.rs.getString("total"),advance,bal,dbcon.rs.getString("date"),dbcon.rs.getString("delivery_date"),dbcon.rs.getString("status")};
                dataSet.addRow(data);
            }
                jTable1.setModel(dataSet);
    } catch (Exception e) {
        e.printStackTrace();
    }
     }
     
     public void getMobile(String item) {
         data = new Vector<>();
       combomodel =new DefaultComboBoxModel();
        try {
             dbcon.rs = dbcon.st.executeQuery("select mobileNO,cusid from user WHERE mobileNo like '"+"%"+item+"%"+"'");
          while (dbcon.rs.next()) {                
                 combomodel.addElement(dbcon.rs.getString("mobileNo"));
                 data.addElement(dbcon.rs.getString("cusid"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        comboItemCode1.setModel(combomodel);
     }
     
     void getItemOnDate(String item){
         combomodel =new DefaultComboBoxModel();
        try {
              dbcon.rs = dbcon.st.executeQuery("select bill_no from bill_record WHERE date = '"+item+"'");
            while (dbcon.rs.next()) {  
                   combomodel.addElement(dbcon.rs.getString("bill_no"));
            }
                  jComboBox1.setModel(combomodel);
         } catch (Exception e) {
            System.out.println("get item " + e);
        }
         
         
     }
     
      void getBill(){
         combomodel =new DefaultComboBoxModel();
        try {
              dbcon.rs = dbcon.st.executeQuery("select bill_no from bill_record");
            while (dbcon.rs.next()) {  
                   combomodel.addElement(dbcon.rs.getString("bill_no"));
            }
                  jComboBox1.setModel(combomodel);
         } catch (Exception e) {
            System.out.println("get item " + e);
        }
      }
     
       void getBill(int start,int stop){
         combomodel =new DefaultComboBoxModel();
        try {
              dbcon.rs = dbcon.st.executeQuery("select bill_no from bill_record where bill_no >= '"+start+"' AND bill_no <= '"+stop+"'");
            while (dbcon.rs.next()) {  
                   combomodel.addElement(dbcon.rs.getString("bill_no"));
            }
                  jComboBox1.setModel(combomodel);
         } catch (Exception e) {
            System.out.println("get item " + e);
        }
      }
     
      public void getMobileItems(String key) {
            combomodel =new DefaultComboBoxModel();
        try {
              dbcon.rs = dbcon.st.executeQuery("select * from bill_record WHERE cusid = '"+key+"'");
            while (dbcon.rs.next()) {  
                   combomodel.addElement(dbcon.rs.getString("bill_no"));
            }
                  jComboBox1.setModel(combomodel);
         } catch (Exception e) {
            System.out.println("get item " + e);
        }
    }
}
