package laundry;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author damhiesax
 */
public class UpdateBillingamount extends javax.swing.JFrame {
 DbConnect dbcon = new DbConnect();
  DbConnect dbcon2 = new DbConnect();
  FormatDate fDate = new FormatDate();
   Date d,dd;
   
   DefaultTableModel dataSet;
   int j=0,dt=0;
    /**
     * Creates new form UpdateBillingamount
     */
    public UpdateBillingamount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateChooserCombo3 = new datechooser.beans.DateChooserCombo();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setText("UPDATE BILLING AMOUNT");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 20, 310, 30);

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 10, 640, 50);

        dateChooserCombo3.setCurrentView(new datechooser.view.appearance.AppearancesList("Light",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateChooserCombo3.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            dateChooserCombo3OnCommit(evt);
        }
    });
    jPanel1.add(dateChooserCombo3);
    dateChooserCombo3.setBounds(50, 160, 110, 20);

    jButton1.setText("Export To Excel");
    jPanel1.add(jButton1);
    jButton1.setBounds(40, 90, 130, 23);

    jButton2.setText("View all");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton2);
    jButton2.setBounds(220, 90, 90, 23);

    jButton3.setText("Close");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton3);
    jButton3.setBounds(360, 90, 80, 23);

    jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jPanel1.add(jLabel3);
    jLabel3.setBounds(30, 80, 640, 50);

    jButton4.setText("View");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton4);
    jButton4.setBounds(210, 160, 90, 23);

    jTable1 = new javax.swing.JTable(){
        public boolean isCellEditable(int row,int column){
            return false;
        }
    };
    jTable1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {},
            {},
            {},
            {}
        },
        new String [] {

        }
    ));
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jPanel1.add(jScrollPane1);
    jScrollPane1.setBounds(40, 190, 610, 220);

    jLabel4.setText("Bill No");
    jPanel1.add(jLabel4);
    jLabel4.setBounds(100, 450, 28, 14);

    jLabel5.setText("Bill To");
    jPanel1.add(jLabel5);
    jLabel5.setBounds(100, 490, 27, 14);

    jLabel6.setText("Phone No");
    jPanel1.add(jLabel6);
    jLabel6.setBounds(80, 530, 70, 14);

    jTextField1.setEditable(false);
    jTextField1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.add(jTextField1);
    jTextField1.setBounds(160, 450, 80, 20);

    jTextField2.setEditable(false);
    jTextField2.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.add(jTextField2);
    jTextField2.setBounds(160, 490, 190, 20);

    jTextField3.setEditable(false);
    jTextField3.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.add(jTextField3);
    jTextField3.setBounds(160, 530, 190, 20);

    jLabel7.setText("Net Amount");
    jPanel1.add(jLabel7);
    jLabel7.setBounds(60, 570, 80, 14);

    jTextField4.setEditable(false);
    jTextField4.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.add(jTextField4);
    jTextField4.setBounds(160, 570, 190, 20);

    jLabel8.setText("Payed Date");
    jPanel1.add(jLabel8);
    jLabel8.setBounds(60, 600, 90, 14);

    jLabel9.setText("Date");
    jPanel1.add(jLabel9);
    jLabel9.setBounds(160, 600, 180, 20);

    jLabel10.setText("Collection Amount");
    jPanel1.add(jLabel10);
    jLabel10.setBounds(370, 460, 130, 14);

    jLabel11.setText("Bill Balance");
    jPanel1.add(jLabel11);
    jLabel11.setBounds(420, 500, 100, 14);

    jTextField5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField5ActionPerformed(evt);
        }
    });
    jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            jTextField5KeyReleased(evt);
        }
    });
    jPanel1.add(jTextField5);
    jTextField5.setBounds(520, 450, 130, 20);

    jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            jTextField6KeyReleased(evt);
        }
    });
    jPanel1.add(jTextField6);
    jTextField6.setBounds(520, 490, 130, 20);

    jButton5.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
    jButton5.setText("Update");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
        }
    });
    jPanel1.add(jButton5);
    jButton5.setBounds(490, 540, 90, 27);

    jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jPanel1.add(jLabel12);
    jLabel12.setBounds(30, 140, 640, 490);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateChooserCombo3OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserCombo3OnCommit
        // TODO add your handling code here:
    }//GEN-LAST:event_dateChooserCombo3OnCommit

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 int a = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to close app");
        if (a == JOptionPane.YES_OPTION) {
           this.setVisible(false);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       dt=1;
        j=0; 
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
        String  startDate = fDate.getDateFormat(dateChooserCombo3.getText());
          d = new Date(startDate);
        dataSet = new DefaultTableModel();
        dataSet.addColumn("S/N");
        dataSet.addColumn("BILL_NO");
        dataSet.addColumn("CUS_ID");
       dataSet.addColumn("TOTAL");
       dataSet.addColumn("COLLECTION-AMT");
        dataSet.addColumn("BAL");
        dataSet.addColumn("DATE");
         dataSet.addColumn("LAST PAY DATE");
             gatData(dateFormat.format(d));
        
     dt=0;   
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        j=0;
        dataSet = new DefaultTableModel();
        dataSet.addColumn("S/N");
        dataSet.addColumn("BILL_NO");
        dataSet.addColumn("CUS_ID");
       dataSet.addColumn("TOTAL");
       dataSet.addColumn("COLLECTION-AMT");
        dataSet.addColumn("BAL");
        dataSet.addColumn("DATE");
         dataSet.addColumn("LAST PAY DATE");
        gatData("");
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    shareData(jTable1.getSelectedRow());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      if(jTextField5.getText().isEmpty()||jTextField6.getText().isEmpty()){
        JOptionPane.showMessageDialog(rootPane, "Please Specify Balance Or Amount Collected");
        jTextField5.requestFocus();
          return;
      }
        update(jTextField5.getText(),jTextField6.getText());
        jButton2ActionPerformed(null);
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
            if(jTextField5.getText().isEmpty()){
 
        return;
        } 
        Object ch = evt.getKeyChar();
            String cha = ch.toString();
             if (!"1234567890\b\n".contains(cha)) {
                jTextField5.setText(jTextField5.getText().substring(0, (jTextField5.getText().length() - 1)));
                return;
            }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
if(jTextField6.getText().isEmpty()){
 
        return;
        } 
        Object ch = evt.getKeyChar();
            String cha = ch.toString();
             if (!"1234567890\b\n".contains(cha)) {
                jTextField6.setText(jTextField6.getText().substring(0, (jTextField6.getText().length() - 1)));
                return;
            }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateBillingamount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateBillingamount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateBillingamount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateBillingamount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateBillingamount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

 void gatData(String data){
   double advance=0;
    double bal=0;
    String date="";
    try {
        if (dt==1) {
          dbcon.rs = dbcon.st.executeQuery("select * from bill_record WHERE bill_record.date = '"+data+"'");
                   
        } else {
             dbcon.rs = dbcon.st.executeQuery("select * from bill_record");
         
        }
           while (dbcon.rs.next()) { 
                  dbcon2.rs = dbcon2.st.executeQuery("select * from update_payment WHERE bill_no = '"+dbcon.rs.getString("bill_no")+"' ORDER BY id");
                    while (dbcon2.rs.next()) {                        
                      advance+=dbcon2.rs.getDouble("amt"); 
                      bal=dbcon2.rs.getDouble("balance");
                      date=dbcon2.rs.getString("date");
                    }
                Object[] dat = new Object[]{++j,dbcon.rs.getString("bill_no"),dbcon.rs.getString("cusid"),dbcon.rs.getString("total"),advance,bal,dbcon.rs.getString("date"),date};
                dataSet.addRow(dat);
            }
                jTable1.setModel(dataSet);
    } catch (Exception e) {
        e.printStackTrace();
    }
 }
 
  void shareData(int sel){
  jTextField1.setText(jTable1.getValueAt(sel, 1).toString());
   jTextField2.setText(jTable1.getValueAt(sel, 2).toString());
      try {
       dbcon2.rs = dbcon2.st.executeQuery("select mobileNo from user WHERE cusid = '"+jTextField2.getText()+"'");
                    if (dbcon2.rs.next()) {                        
                      jTextField3.setText(dbcon2.rs.getString("mobileNo"));
                }   
         jTextField4.setText(jTable1.getValueAt(sel, 3).toString());
                  jTextField5.setText(jTable1.getValueAt(sel, 4).toString());
         jTextField6.setText(jTable1.getValueAt(sel, 5).toString());
         jLabel9.setText(jTable1.getValueAt(sel, 7).toString());

      } catch (Exception e) {
      }
   
  }
   private void update(String adv,String bal) {
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
        try {
            dbcon.ps = dbcon.con.prepareStatement("delete from update_payment where bill_no='"+jTextField1.getText()+"'");
            dbcon.ps.execute();
             dbcon.ps = dbcon.con.prepareStatement("insert into update_payment values (?,?,?,?,?)");
                    dbcon.ps.setInt(1, 0);
                    dbcon.ps.setString(2, jTextField1.getText());
                    dbcon.ps.setString(3, adv);
                    dbcon.ps.setString(4, bal);
                    dd=new Date();
                    dd=new Date(dd.getTime());
                    dbcon.ps.setString(5, dateFormat.format(dd));
                    dbcon.ps.executeUpdate();
                    
         } catch (Exception e) {
            System.out.println("red " + e.getMessage());
        }
        JOptionPane.showMessageDialog(rootPane, "Data Updated");
    }
   void clear(){
   jTextField1.setText(null); 
    jTextField2.setText(null);
     jTextField3.setText(null);
      jTextField4.setText(null);
       jTextField5.setText(null);
        jTextField6.setText(null);
        jLabel9.setText("date");
  }
}
