package laundry;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author damhiesax
 */
public class UserReg extends javax.swing.JFrame {

    login newLog = new login();
    DbConnect dbcon = newLog.dbcon;
    ResultSetMetaData md;
    String firstname, lastname, PassWord, address, mobileNo, administrator, username, Userid;
    Connection con;
    ResultSet rs;
    PreparedStatement ps;
    Statement st;
    Vector<String> data = new Vector<String>();

    public static String[] rowData;

    /**
     * Creates new form UserReg
     */
    public UserReg() {
        initComponents();
        setTitle("Staff Registration Page");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Registraion");
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setText("First Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 40, 90, 14);

        jLabel2.setText("Last Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 80, 90, 14);

        jLabel3.setText("Address");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 120, 90, 14);

        jLabel4.setText("Username");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 200, 90, 14);

        jLabel5.setText("Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 240, 90, 14);

        jLabel6.setText("Administrator");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 280, 80, 20);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(110, 40, 230, 20);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(110, 80, 230, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(110, 120, 230, 18);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(110, 160, 230, 20);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(110, 200, 230, 20);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(110, 240, 230, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select type", "Sales", "Admin" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(110, 280, 230, 23);

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 330, 100, 27);

        jButton2.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(130, 330, 110, 27);

        jButton3.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(250, 330, 100, 27);

        jLabel8.setText("Phone No");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 160, 70, 14);

        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 20, 350, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addnew();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jPasswordField1.setText("");

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

    void clear() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jPasswordField1.setText("");
    }

    void addnew() {
        String emt = "";
        if (jTextField1.getText().equals(emt)) {
            JOptionPane.showMessageDialog(rootPane, "Name  required");
            return;
        }
        if (jPasswordField1.getText().equals(emt)) {
            JOptionPane.showMessageDialog(rootPane, "password required");
            return;
        }
        if (jTextField2.getText().equals(emt)) {
            JOptionPane.showMessageDialog(rootPane, "last Name required");
            return;
        }
        if (jTextField3.getText().equals(emt)) {
            JOptionPane.showMessageDialog(rootPane, "Address required");
            return;
        }
        if (jTextField4.getText().equals(emt)) {
            JOptionPane.showMessageDialog(rootPane, "Username required");
            return;
        }
        if (jTextField5.getText().equals(emt)) {
            JOptionPane.showMessageDialog(rootPane, "Mobile No plssss!!");
            return;
        }
        if (checkForPresence()) {
            JOptionPane.showMessageDialog(rootPane, "user already exit");
        } else {
            String userid = Math.round((Math.random() * 999999)) + "";
            userid = "CLNR".concat(userid);
            try {
                dbcon.ps = dbcon.con.prepareStatement("insert into loginpage VALUES(?,?,?,?,?,?,?,?,?)");
                dbcon.ps.setInt(1, 0);
                dbcon.ps.setString(2, userid);
                dbcon.ps.setString(3, jTextField1.getText());
                dbcon.ps.setString(4, jTextField2.getText());
                dbcon.ps.setString(5, jTextField3.getText());
                dbcon.ps.setString(6, jTextField4.getText());
                dbcon.ps.setString(7, jTextField5.getText());
                dbcon.ps.setString(8, jPasswordField1.getText());
                dbcon.ps.setString(9, jComboBox1.getSelectedItem().toString());
                dbcon.ps.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "user registered successfully..");
            } catch (Exception g) {
                System.out.println("user not registered successfully.." + g);
            }
        }
        clear();
    }

    public void cardnum() {
        try {
            int summ = 0;
            String SQLCommand2 = "select Userid from authenAgent";
            dbcon.rs = dbcon.st.executeQuery(SQLCommand2);
            ResultSetMetaData md2 = dbcon.rs.getMetaData();
            int nColumns2 = md2.getColumnCount();
            while (dbcon.rs.next()) {
                rowData = new String[nColumns2];
                for (int i = 0; i < nColumns2; i++) {
                    summ = summ + 1;
                    rowData[i] = dbcon.rs.getObject(i + 1).toString();
                    data.addElement(rowData[i]);
                }
            }
            Userid += summ;
            System.out.println("Userid  " + Userid);
        } catch (Exception e) {
            System.out.println("Card number Error" + e);
        }
    }

    boolean checkForPresence() {
        boolean present = false;
        try {
            dbcon.rs = dbcon.st.executeQuery("select * from loginpage where username='"+jTextField5.getText()+"' and password='"+jPasswordField1.getText()+"' '");
        
           if (dbcon.rs.next()) { 
           present=true;
           }
        } catch (Exception g) {
            System.out.println("" + g);
        }
//
        return present;
//
//    }

    }
}
